#!/bin/bash
filename=$1
if [ -e $filename ];then
	IMG_CHARS=`identify "$1" | cut -f 3 -d' '`
	WIDTH=`echo $IMG_CHARS | cut -d'x' -f 1`
	HEIGHT=`echo $IMG_CHARS | cut -d'x' -f 2`
	if [ $WIDTH -gt 256 ];then
		/show/listecho "Resize image to growl icon (128x128)"
		convert $1 -resize 128x128 $1
	else
		echo "no resize needed"
	fi
fi
