#!/bin/bash
if [ $# -eq 4 ];then
hostname="$1"
password="$2"
title="$3"
description="$4"
        python /opt/piget/growl/python/growlNoIcon.py "$hostname" "$password" "$title" "$description"
else
        /show/errorBox "Wrong Arguments"
        /show/usage "/do/growl/send hostname password title description"
        /show/example '/do/growl/send "192.168.0.1" "batteryStaple" "Test" "hello world"'
fi

